# Generated by Django 2.2.7 on 2019-11-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_testadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestAdmin',
            new_name='TestmodelAdmin',
        ),
    ]
