# Generated by Django 2.2.7 on 2019-11-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_auto_20191117_2216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestmodelAdmin',
            new_name='TestAdmin',
        ),
    ]
