# Generated by Django 2.2.7 on 2019-11-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_auto_20191117_2224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestAdmin',
        ),
    ]
